version: '3'
services:
  theia:
    image: "theiaide/theia-full:latest"
    volumes:
      - "/opt/cdt-data/theia/${USERNAME}/.ssh:/home/theia/.ssh"
      - "/opt/cdt-data/theia/${USERNAME}/maven-local-repo:/home/theia/.m2/repository"
      - "/opt/cdt-cert/cacerts:/etc/ssl/certs/java/cacerts:ro"
    environment:
      GIT_URL: ${GIT_URL}
    ports:
      - 3000
      - 8080
    networks:
      - cdt
    restart: always
    labels:
      - traefik.backend=theia
      - traefik.frontend.rule=Host:theia-${COMPOSE_PROJECT_NAME}.${BASE_DOMAIN}
      - traefik.docker.network=cdt
      - traefik.port=3000

networks:
  cdt:
    external: true
