#!/bin/bash

if [[ ! -z "${DEBUG}" ]]; then
  set -o xtrace
  echo arguments: USERNAME: $1 GIT_URL: $2 ACTION: $3
fi

USERNAME=$1
GIT_URL=$2

workspace_name=$(echo -n ${USERNAME}_${GIT_URL} | md5sum | awk '{print $1}' | cut -c1-8 )

export COMPOSE_PROJECT_NAME=${workspace_name}
export BASE_DOMAIN="precdt.devopswise.co.uk"

if [ "$3" = "up" ]; then
  docker-compose up -d
else
  docker-compose down
fi

retVal=$?

if [ $retVal -ne 0 ]; then
  echo "Error starting workspace"
else
  echo $workspace_name
fi
exit $retVal