---
application:
  springfox:
    documentation:
      swagger:
        v2:
          path: /api-docs
server:
  contextPath: /
  port: "8080"
logging:
  file: /tmp/cdtportal.log
  level:
    com:
      devopswise: DEBUG
      offbytwo:
        jenkins: DEBUG
    org:
      hibernate:
        SQL: DEBUG
      keycloak: DEBUG
endpoints:
  metrics:
    sensitive: false
  logfile:
    sensitive: false
  dump:
    sensitive: false
info:
  app:
    name: cdtportal
    description: RestAPI to create and configure projects in jenkins,gitea,rocketchat
    version: 0.9.2
spring:
  datasource:
    url: jdbc:h2:file:/data/h2db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: "false"
  h2:
    console:
      enabled: "true"
      path: /h2-console
      settings:
        web-allow-others: "true"
  jpa:
    open-in-view: "true"
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  ldap:
    urls: ldap://precdt.devopswise.co.uk:389
    base: dc=devopswise,dc=co,dc=uk
    username: cn=admin,dc=devopswise,dc=co,dc=uk
    password: password
jenkins:
  baseUrl: https://jenkins.precdt.devopswise.co.uk
  username: admin
  password: password
rocketChat:
  baseUrl: https://rocketchat.precdt.devopswise.co.uk
  username: local.admin
  password: password
  debug: "true"
gitea:
  baseUrl: https://gitea.precdt.devopswise.co.uk/api/v1
  username: local.admin
  password: password
  debug: "true"
cdt:
  baseDomain: "precdt.devopswise.co.uk"
keycloak:
  auth-server-url: https://keycloak.precdt.devopswise.co.uk/auth
  credentials:
    secret: "dbe7ed61-a628-4487-bdc2-123840111a95"
  realm: master
  resource: cdtportal
  ssl-required: external
  enable-basic-auth: false
  principal-attribute: username
  security-constraints[0]:
    securityCollections[0]:
      name: static-resources
      patterns[0]: /css/*
      patterns[1]: /fonts/*
      patterns[2]: /js/*
  security-constraints[1]:
    authRoles[0]: admin
    securityCollections[0]:
      name: application
      patterns[0]: /*