---
application:
  springfox:
    documentation:
      swagger:
        v2:
          path: /api-docs
server:
  contextPath: /
  port: "8080"
logging:
  file: /tmp/cdtportal.log
  level:
    com:
      devopswise: DEBUG
      offbytwo:
        jenkins: DEBUG
    org:
      hibernate:
        SQL: DEBUG
endpoints:
  metrics:
    sensitive: false
  logfile:
    sensitive: false
  dump:
    sensitive: false
info:
  app:
    name: cdtportal
    description: RestAPI to create and configure projects in jenkins,gitea,rocketchat
    version: latest
spring:
  datasource:
    url: jdbc:h2:file:/tmp/h2db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: "false"
  h2:
    console:
      enabled: "true"
      path: /h2-console
  jpa:
    open-in-view: "true"
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  ldap:
    urls: ldap://cdt.cdt.devopswise.co.uk:389
    base: dc=devopswise,dc=co,dc=uk
    username: cn=admin,dc=devopswise,dc=co,dc=uk
    password: Jah8qOetood
jenkins:
  baseUrl: https://jenkins.cdt.devopswise.co.uk
  username: admin
  password: Jah8qOetood
rocketChat:
  baseUrl: https://rocketchat.cdt.devopswise.co.uk
  username: local.admin
  password: Jah8qOetood
  debug: "true"
gitea:
  baseUrl: https://gitea.cdt.devopswise.co.uk/api/v1
  username: local.admin
  password: Jah8qOetood
  debug: "true"
cdt:
  baseDomain: "cdt.devopswise.co.uk"
keycloak:
  auth-server-url: "https://keycloak.cdt.devopswise.co.uk/auth"
  credentials:
    secret: "8a34302f-02d5-42fc-a076-c4e17587714b"
  realm: master
  resource: cdt
  ssl-required: external
  enable-basic-auth: false
  principal-attribute: username
  security-constraints[0]:
    securityCollections[0]:
      name: static-resources
      patterns[0]: /css/*
      patterns[1]: /fonts/*
      patterns[2]: /js/*
  security-constraints[1]:
    authRoles[0]: admin
    securityCollections[0]:
      name: application
      patterns[0]: /*
  security-constraints[2]:
    authRoles[0]: cdt-user
    securityCollections[0]:
      name: application
      patterns[0]: /*
